const { writeFile, existsSync, mkdirSync } = require('fs');
require('dotenv').config();

function writeFileUsingFS(targetPath, environmentFileContent) {
    writeFile(targetPath, environmentFileContent, function (err) {
        if (err) {
            console.log(err);
        }
        if (environmentFileContent !== '') {
            console.log(`Wrote variables to ${targetPath}`);
        }
    });
}

const envDirectory = './src/environments';
const envFile = 'environment.ts';

if (!existsSync(envDirectory)) {
    mkdirSync(envDirectory);
}

const environmentFileContent = `// This file was autogenerated by dynamically running scripts/setEnv.ts and using dotenv for managing API key secrecy
export const environment = {
    production: true,
    apiUrl: '${process.env['API_URL']}'
};
`;

writeFileUsingFS(`${envDirectory}/${envFile}`, environmentFileContent);
