name: Build and Deploy Cloud Functions

on:
  push:
    branches: [ 'main' ]
    paths: [ 'functions/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Build TypeScript
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v14.4.0
        with:
          args: deploy --only functions
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
